In [7]:
#ler arquivo csv
import pandas as pd 

ordens_servico_sujas = pd.read_csv('../data/ordens_servico_sujas.csv')
display(ordens_servico_sujas)

    id_os cliente        servico  valor       status     data_os
0       1    João  Troca de Óleo  120.0   Finalizado  2026-01-05
1       2   Maria    Alinhamento   80.0   finalizado  2026-01-06
2       3    João          Freio  350.0  Finalizado   2026-01-08
3       4  Carlos  Troca de Óleo  120.0     Pendente  2026-01-09
4       5   Maria          Freio    NaN   Finalizado  2026-01-10
5       6     Ana        Revisão  500.0   Finalizado  2026-01-12
6       7    João        Revisão  500.0   FINALIZADO  2026-01-15
7       8  Carlos    Alinhamento   80.0   Finalizado  2026-01-16
8       9     Ana          Freio  320.0     Pendente  2026-01-18
9      10   Maria        Revisão  500.0   Finalizado  2026-01-20
10     11   Pedro        Bateria  450.0    Cancelado  2026-01-21
11     12     Ana  Troca de Óleo  120.0   finalizado  2026-01-22

In [18]:
#limpar a coluna 'status'

ordens_servico_sujas['status'] = ordens_servico_sujas['status'].str.strip().str.lower().str.capitalize().fillna('Pendente')

display(ordens_servico_sujas)

    id_os cliente        servico  valor      status     data_os
0       1    João  Troca de Óleo  120.0  Finalizado  2026-01-05
1       2   Maria    Alinhamento   80.0  Finalizado  2026-01-06
2       3    João          Freio  350.0  Finalizado  2026-01-08
3       4  Carlos  Troca de Óleo  120.0    Pendente  2026-01-09
4       5   Maria          Freio    NaN  Finalizado  2026-01-10
5       6     Ana        Revisão  500.0  Finalizado  2026-01-12
6       7    João        Revisão  500.0  Finalizado  2026-01-15
7       8  Carlos    Alinhamento   80.0  Finalizado  2026-01-16
8       9     Ana          Freio  320.0    Pendente  2026-01-18
9      10   Maria        Revisão  500.0  Finalizado  2026-01-20
10     11   Pedro        Bateria  450.0   Cancelado  2026-01-21
11     12     Ana  Troca de Óleo  120.0  Finalizado  2026-01-22

In [19]:
#limpando valores ausentes

ordens_servico_sujas['valor'] = ordens_servico_sujas['valor'].fillna(0)

display(ordens_servico_sujas)

    id_os cliente        servico  valor      status     data_os
0       1    João  Troca de Óleo  120.0  Finalizado  2026-01-05
1       2   Maria    Alinhamento   80.0  Finalizado  2026-01-06
2       3    João          Freio  350.0  Finalizado  2026-01-08
3       4  Carlos  Troca de Óleo  120.0    Pendente  2026-01-09
4       5   Maria          Freio    0.0  Finalizado  2026-01-10
5       6     Ana        Revisão  500.0  Finalizado  2026-01-12
6       7    João        Revisão  500.0  Finalizado  2026-01-15
7       8  Carlos    Alinhamento   80.0  Finalizado  2026-01-16
8       9     Ana          Freio  320.0    Pendente  2026-01-18
9      10   Maria        Revisão  500.0  Finalizado  2026-01-20
10     11   Pedro        Bateria  450.0   Cancelado  2026-01-21
11     12     Ana  Troca de Óleo  120.0  Finalizado  2026-01-22

In [ ]:
#transformando datas str em datetime 

ordens_servico_sujas['data_os'] = pd.to_datetime(ordens_servico_sujas['data_os'])

ordens_servico_sujas.info()

display(ordens_servico_sujas)

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id_os    12 non-null     int64
 1   cliente  12 non-null     str
 2   servico  12 non-null     str
 3   valor    12 non-null     float64
 4   status   12 non-null     str
 5   data_os  12 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 991.0 bytes

    id_os cliente        servico  valor      status    data_os
0       1    João  Troca de Óleo  120.0  Finalizado 2026-01-05
1       2   Maria    Alinhamento   80.0  Finalizado 2026-01-06
2       3    João          Freio  350.0  Finalizado 2026-01-08
3       4  Carlos  Troca de Óleo  120.0    Pendente 2026-01-09
4       5   Maria          Freio    0.0  Finalizado 2026-01-10
5       6     Ana        Revisão  500.0  Finalizado 2026-01-12
6       7    João        Revisão  500.0  Finalizado 2026-01-15
7       8  Carlos    Alinhamento   80.0  Finalizado 2026-01-16
8       9     Ana          Freio  320.0    Pendente 2026-01-18
9      10   Maria        Revisão  500.0  Finalizado 2026-01-20
10     11   Pedro        Bateria  450.0   Cancelado 2026-01-21
11     12     Ana  Troca de Óleo  120.0  Finalizado 2026-01-22

In [25]:
#nomeando nova tabela tratada
ordens_tratadas = ordens_servico_sujas

display(ordens_tratadas)

    id_os cliente        servico  valor      status    data_os
0       1    João  Troca de Óleo  120.0  Finalizado 2026-01-05
1       2   Maria    Alinhamento   80.0  Finalizado 2026-01-06
2       3    João          Freio  350.0  Finalizado 2026-01-08
3       4  Carlos  Troca de Óleo  120.0    Pendente 2026-01-09
4       5   Maria          Freio    0.0  Finalizado 2026-01-10
5       6     Ana        Revisão  500.0  Finalizado 2026-01-12
6       7    João        Revisão  500.0  Finalizado 2026-01-15
7       8  Carlos    Alinhamento   80.0  Finalizado 2026-01-16
8       9     Ana          Freio  320.0    Pendente 2026-01-18
9      10   Maria        Revisão  500.0  Finalizado 2026-01-20
10     11   Pedro        Bateria  450.0   Cancelado 2026-01-21
11     12     Ana  Troca de Óleo  120.0  Finalizado 2026-01-22

In [30]:
#filtrar para apenas ordens finalizadas

ordens_tratadas = ordens_tratadas[ordens_tratadas['status'] == 'Finalizado']

display(ordens_tratadas)

    id_os cliente        servico  valor      status    data_os
0       1    João  Troca de Óleo  120.0  Finalizado 2026-01-05
1       2   Maria    Alinhamento   80.0  Finalizado 2026-01-06
2       3    João          Freio  350.0  Finalizado 2026-01-08
4       5   Maria          Freio    0.0  Finalizado 2026-01-10
5       6     Ana        Revisão  500.0  Finalizado 2026-01-12
6       7    João        Revisão  500.0  Finalizado 2026-01-15
7       8  Carlos    Alinhamento   80.0  Finalizado 2026-01-16
9      10   Maria        Revisão  500.0  Finalizado 2026-01-20
11     12     Ana  Troca de Óleo  120.0  Finalizado 2026-01-22

In [31]:
#total faturado

total_faturado = ordens_tratadas['valor'].sum()

display(f'o valor total faturado foi de R${total_faturado:.2f}')

'o valor total faturado foi de R$2250.00'

In [32]:
#quantidade de ordens finalizadas

quantidade_os = ordens_tratadas.shape[0]

display(f'foram finalizados {quantidade_os} pedidos')

'foram finalizados 9 pedidos'

In [34]:
#cliente com maior faturamento
faturamento_cliente = ordens_tratadas.groupby('cliente')['valor'].sum()

display(faturamento_cliente)

top_cliente = faturamento_cliente.idxmax()
top_faturamento_cliente = faturamento_cliente.max()

display(f'{top_cliente} foi o melhor cliente do periodo, gastando no total R${top_faturamento_cliente:.2f}')

cliente
Ana       620.0
Carlos     80.0
João      970.0
Maria     580.0
Name: valor, dtype: float64

'João foi o melhor cliente do periodo, gastando no total R$970.00'

In [36]:
#serviço com maior valor médio

media_servico = ordens_tratadas.groupby('servico')['valor'].mean()

display(media_servico)

top_servico = media_servico.idxmax()
top_media_servico = media_servico.max()

display(f'{top_servico} trouxe a maior media de faturamento: R${top_media_servico:.2f}')

servico
Alinhamento       80.0
Freio            175.0
Revisão          500.0
Troca de Óleo    120.0
Name: valor, dtype: float64

'Revisão trouxe a maior media de faturamento: R$500.00'

In [37]:
#primeiro e último dia com ordem finalizada

primeira_data = ordens_tratadas['data_os'].min()
ultima_data = ordens_tratadas['data_os'].max()

display(f'o primeiro pedido foi registrado em {primeira_data} e o ultimo em {ultima_data}')

'o primeiro pedido foi registrado em 2026-01-05 00:00:00 e o ultimo em 2026-01-22 00:00:00'

In [39]:
# criar relatorio

relatorio = pd.DataFrame({
    'metrica': [
        'total_faturado',
        'qtd_os_finalizadas',
        'cliente_maior_faturamento',
        'valor_cliente_maior_faturamento',
        'servico_maior_media',
        'valor_servico_maior_media',
        'primeira_data_finalizada',
        'ultima_data_finalizada'
    ],
    'valor': [
        total_faturado,
        quantidade_os,
        top_cliente,
        top_faturamento_cliente,
        top_servico,
        top_media_servico,
        primeira_data,
        ultima_data
    ]
}
)

display(relatorio)

                           metrica                valor
0                   total_faturado               2250.0
1               qtd_os_finalizadas                    9
2        cliente_maior_faturamento                 João
3  valor_cliente_maior_faturamento                970.0
4              servico_maior_media              Revisão
5        valor_servico_maior_media                500.0
6         primeira_data_finalizada  2026-01-05 00:00:00
7           ultima_data_finalizada  2026-01-22 00:00:00

In [ ]:
# exportando relatorio
relatorio.to_csv('../output/relatorio.csv', index=False)