In [1]:
#objetivo

# - Qual foi o faturamento total?
# - Qual dia teve maior faturamento?
# - Qual dia teve menPor faturamento?
# - Qual foi o faturamento médio por dia?
# - Quantos dias tiveram vendas registradas?

# passo a passo

# ler arquivo csv
# limpeza e tratamento
# analise

In [2]:
# lendo arquivo
import pandas as pd 

vendas_periodo = pd.read_csv('../data/vendas_periodo.csv')

display(vendas_periodo)

    id_os cliente        servico  valor     data_os
0       1    João  Troca de Óleo    120  2026-01-05
1       2   Maria    Alinhamento     80  2026-01-05
2       3    João          Freio    350  2026-01-06
3       4  Carlos  Troca de Óleo    120  2026-01-06
4       5   Maria          Freio    300  2026-01-08
5       6     Ana        Revisão    500  2026-01-08
6       7    João        Revisão    500  2026-01-10
7       8  Carlos    Alinhamento     80  2026-01-10
8       9     Ana          Freio    320  2026-01-12
9      10   Maria        Revisão    500  2026-01-12
10     11   Pedro        Bateria    450  2026-01-12
11     12     Ana  Troca de Óleo    120  2026-01-15

In [3]:
# limpeza e tratamento
vendas_periodo['data_os'] = pd.to_datetime(vendas_periodo['data_os'])

vendas_periodo.info()
display(vendas_periodo)

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id_os    12 non-null     int64
 1   cliente  12 non-null     str
 2   servico  12 non-null     str
 3   valor    12 non-null     int64
 4   data_os  12 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 778.0 bytes

    id_os cliente        servico  valor    data_os
0       1    João  Troca de Óleo    120 2026-01-05
1       2   Maria    Alinhamento     80 2026-01-05
2       3    João          Freio    350 2026-01-06
3       4  Carlos  Troca de Óleo    120 2026-01-06
4       5   Maria          Freio    300 2026-01-08
5       6     Ana        Revisão    500 2026-01-08
6       7    João        Revisão    500 2026-01-10
7       8  Carlos    Alinhamento     80 2026-01-10
8       9     Ana          Freio    320 2026-01-12
9      10   Maria        Revisão    500 2026-01-12
10     11   Pedro        Bateria    450 2026-01-12
11     12     Ana  Troca de Óleo    120 2026-01-15

In [4]:
# - Qual foi o faturamento total?

faturamento_total = vendas_periodo['valor'].sum()

display(f'o faturamento total foi de R${faturamento_total:.2f}')

'o faturamento total foi de R$3440.00'

In [5]:
# - Qual dia teve maior faturamento?
faturamento_dia = vendas_periodo.groupby('data_os')['valor'].sum()
melhor_dia = faturamento_dia.idxmax()
faturamento_melhor_dia = faturamento_dia.max()

display(f'{melhor_dia} foi o dia com maior faturamento: R${faturamento_melhor_dia:.2f}')

'2026-01-12 00:00:00 foi o dia com maior faturamento: R$1270.00'

In [6]:
# - Qual dia teve menPor faturamento?

pior_dia = faturamento_dia.idxmin()
faturamento_pior_dia = faturamento_dia.min()

display(f'{pior_dia} foi o dia com menor faturamento: R${faturamento_pior_dia:.2f}')

'2026-01-15 00:00:00 foi o dia com menor faturamento: R$120.00'

In [7]:
# - Qual foi o faturamento médio por dia?
media_dia = faturamento_dia.mean()

display(f'{media_dia:.2f} é o ticket medio por dia')

'573.33 é o ticket medio por dia'

In [8]:
# Quantos dias tiveram vendas registradas?
contagem_dias_registrado = faturamento_dia.count()

display(f'foram registrado {contagem_dias_registrado} dias com pedidos')

'foram registrado 6 dias com pedidos'

In [ ]:
# criando relatorio

relatorio = pd.DataFrame({
    'metrica':[
        'total_faturado',
        'dia_maior_faturamento',
        'valor_dia_maior_faturamento',
        'dia_menor_faturamento',
        'valor_dia_menor_faturamento',
        'faturamento_medio_diario',
        'dias_com_vendas'
    ],
    'valor':[
        faturamento_total,
        melhor_dia,
        faturamento_melhor_dia,
        pior_dia,
        faturamento_pior_dia,
        media_dia,
        contagem_dias_registrado
    ]

})

In [12]:
# exportando relatorio csv

relatorio.to_csv('../output/relatorio.csv', index=False)