In [ ]:
# Objetivo

# Qual foi o faturamento total?

# Quanto cada cliente faturou?

# Quantas ordens cada cliente realizou?

# Qual percentual do faturamento total cada cliente representa?

# Qual cliente tem maior participação no faturamento?

In [7]:
# criando df

import pandas as pd 

df = pd.read_csv('../data/clientes_faturamento.csv')
display(df.head(3))

   id_os cliente  valor
0      1    João    120
1      2   Maria     80
2      3    João    350

In [8]:
# Qual foi o faturamento total?
faturamento_total = df['valor'].sum()
display(f'Faturamento total: R${faturamento_total:.2f}')

'Faturamento total: R$4190.00'

In [ ]:
# Quanto cada cliente faturou?

faturamento_cliente = df.groupby('cliente')['valor'].sum()

for cliente, valor in faturamento_cliente.items():
    display(f'{cliente}: R$ {valor:.2f}')

'Ana: R$ 940.00'

'Carlos: R$ 200.00'

'João: R$ 1170.00'

'Maria: R$ 1130.00'

'Pedro: R$ 750.00'

In [15]:
# Quantas ordens cada cliente realizou?

ordens_cliente = df.groupby('cliente')['valor'].count()

for cliente, pedidos in ordens_cliente.items():
    display(f'{cliente} teve {pedidos} pedidos')

'Ana teve 3 pedidos'

'Carlos teve 2 pedidos'

'João teve 4 pedidos'

'Maria teve 4 pedidos'

'Pedro teve 2 pedidos'

In [41]:
# Qual percentual do faturamento total cada cliente representa?

porcentagem_cliente = []
for cliente, valor in faturamento_cliente.items():
    
    display(f'{cliente} representa {valor/faturamento_total*100:.1f}% do faturamento total')

    dados_cliente={'cliente': cliente, '%_faturamento': valor/faturamento_total*100}
    porcentagem_cliente.append(dados_cliente)

porcentagem_cliente = pd.DataFrame(porcentagem_cliente).sort_values('%_faturamento')
porcentagem_cliente['%_faturamento'] = porcentagem_cliente['%_faturamento'].round(1)
porcentagem_cliente.to_csv('../output/porcentagem_cliente.csv', index=False)

display(porcentagem_cliente)

'Ana representa 22.4% do faturamento total'

'Carlos representa 4.8% do faturamento total'

'João representa 27.9% do faturamento total'

'Maria representa 27.0% do faturamento total'

'Pedro representa 17.9% do faturamento total'

  cliente  %_faturamento
1  Carlos            4.8
4   Pedro           17.9
0     Ana           22.4
3   Maria           27.0
2    João           27.9

In [ ]:
# melhor cliente

melhor_cliente = df.groupby('cliente')['valor'].sum().idxmax()

display(f'{melhor_cliente} é o melhor cliente')

'João é o melhor cliente'

In [ ]:
# criando relatorio

relatorio = pd.DataFrame({
    'faturamento_total': faturamento_cliente,
    'qtd_ordens': ordens_cliente,
    'participacao_percentual': faturamento_cliente/faturamento_total*100
})

relatorio['participacao_percentual'] = (
    relatorio['participacao_percentual']
    .round(1)
)

relatorio = (
    relatorio
    .sort_values(
        by='participacao_percentual',
        ascending=False
    )
)

display(relatorio)

         faturamento_total  qtd_ordens  participacao_percentual
cliente
João                  1170           4                     27.9
Maria                 1130           4                     27.0
Ana                    940           3                     22.4
Pedro                  750           2                     17.9
Carlos                 200           2                      4.8

In [ ]:
# exportando relatorio
relatorio.to_csv('../output/relatorio_clientes.csv')